### ISSUE TITLE
Unable to install on Windows 10/11

### ISSUE THREAD

**Issue by Nikunj-1308** [UMB-CS-682-Team-03/tracker#1]
Following the instructions from: https://www.roundup-tracker.org/docs/installation.html#standard-installation

For Windows, I cloned the repository

Then I created the virtual environment
```powershell
python -m venv .
.\Scripts\activate

python -m pip install roundup
```

The installation process hangs on the above command:
```powershell
Collecting roundup
  Downloading roundup-2.3.0.tar.gz (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 15.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... canceled
ERROR: Operation cancelled by user
```

**Comment by patel-malav** [comment]
This was resolved by using WSL instead

**Comment by rouilj** [comment]
Ah, I didn't realize this as your issue on windows 11. If I had known I would have directed you to:

https://wiki.roundup-tracker.org/ReleaseErrata
