### ISSUE TITLE
Enhancement: Frontend Testing Framework Implementation with Selenium

### ISSUE THREAD

**Issue by BharathKanama** [UMB-CS-682-Team-03/tracker#15]
Our testing primarily focuses on backend functionality, leaving frontend coverage lacking.
To remedy this, we propose implementing a robust frontend testing framework using Selenium. Selenium's capabilities make it ideal for automated browser testing, including popup management.

Additionally, comprehensive documentation on popup handling with Selenium will be developed to aid testing efforts.

**Comment by rouilj** [comment]
I use splinter which is a python based script system for selenium. You can handle popups reference
this issue: https://github.com/cobrateam/splinter/issues/473

I drive my tracker and capture screenshots for the documentation.

Worth a look unless you have another framework in mind.

**Comment by BharathKanama** [comment]
uploaded the docs in README.md
