### ISSUE TITLE
Next link shown when there are no more items to show.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#23]
This is due to a bug in the underlying Roundup REST interface tracked at
https://issues.roundup-tracker.org/issue2551328.

The bug happens when:

  * the number of items displayed in the search pane is a multiple of the total
    number of results (e.g. total is 20 and size is 10, total is 21 and size is 7)
  * you are on the page that shows the last result

The rest response for the page showing the last result incorrectly sets the next link
even though accessing the next link returns no data. The response when requesting the
next link does not have a next link.

Also due to another Roundup bug, the count of the total number of results is incorrect,
so there is nothing the web component can do to detect this case. The fix has to come from
Roundup.

**Comment by rouilj** [comment]
@patel-malav you and @BharathKanama discovered/worked on this right?

I want to get the attribution right in the changelog for roundup. Bharath, if it was you how do you want
your name listed? Is "Bharath Kanama" your preference?

I have a solution for this issue that works. I am waiting on a second review of my proposal before I commit it.

Also the solution fixes the incorrect value returned in @total_size (#17), so you can re-enable the "...10-20 out of X..."
display to the pagination control panel when it is committed.

**Comment by rouilj** [comment]
Fixed the issue upstream and committed. Closed https://issues.roundup-tracker.org/issue2551328. Still
waiting to find out how @BharathKanama want's his name listed.

Before closing this issue on github, please pull from upstream and get your local dev environments running the
current code.

**Comment by BharathKanama** [comment]
@rouilj yes john, you can keep my name as Bharath Kanama itself.

**Comment by patel-malav** [comment]
This checked and now works correctly
