### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by patel-malav** [UMB-CS-682-Team-03/tracker#25]
The usage documentation and code documentation is missing

**Comment by rouilj** [comment]
The doc should cover:

* user guide for roundup-classhelper
   * describe why we need it
   * describe the three parts of the classhelper
      1. search section (which may be optional)
      2. select/info table section (which may be empty if a search pane is shown).
          includes pagination controls
          It may or may not have a checkbox for selection (if there is no associated form field in the classhelper url,
          it is just an information box with no select capability)
      3) accumulator/submit shows the items selected by the select section. May be missing if the select/info is in info
          mode
    * describe using it with keyboard (include tab order/arrows) and mouse
  * admin guide for deploying roundup-classhelper to an existing tracker
     * the tags to use and where to put them
     * the attributes of the helper and attribute value syntax
     * the attributes to use on a user classhelper to emulate the normal user classhelper (username, roles).
        If we can't get roles as a dropdown, mention that it is text only match
     * how fallback to the older classhelper works
     * Error conditions shown to the user and how to further debug (e.g. pull up console and look at results).
  * developer guide - most of this I think is in README.txt, but it should include:
     * how to install packages required to run the tests
     * how to run pytest to run the tests
     * what is tested  e.g.
        * the classhelper for the superseeder property is activated; admin is searched for and the helper is closed
           verify that the selected items are in the main form 
        * etc. You can simplify by just listing the classhelper classes that al are tested the same way (some without search),
           some with search, some with preexisting content, some in info only mode.

I suggest each of you writes one major section. I am not sure if info mode is implemented. It think it was identified
but I am not sure I followed up on it.

**Comment by rouilj** [comment]
Also add info on  how to refresh classhelper.js. using ctl-shift-R in the popup window empties it.
I can keep the developer console open with disable caching to get the css file updated. But there seems like there should be an easier way.

**Comment by rouilj** [comment]
Also for the admin guide cover installation. I think there are 4 components:

  1. install classhelper.js in html directory
  2. install classhelper.css in html directory
  3. install translation endpoint (_generic.json) as _generic.translation.
      (This may require changing the endpoint (@template) in the js code. This requires an
      updated roundup where the roundup code has support for setting the template's
      mime type in the html response.)
  4. add the /rest/roles endpoint via interfaces.py

I think that's it.

**Comment by patel-malav** [comment]
Addressed the last comment, the docs were updated closing the issue
