### ISSUE TITLE
searchWith dropdown option (refine)

### ISSUE THREAD

**Issue by patel-malav** [UMB-CS-682-Team-03/tracker#27]
The current implementation of searchWith is missing the ability to define a field as dropdown

eg.
```html
<roundup-classhelper searchWith="username,phone,roles:<<??>>">
   <a>...</a>
</roundup-classhelper>
```

Though I can fetch keywords, status, priority but how can I get roles? as they are properties of user

**Comment by rouilj** [comment]
I'm confused, isn't your classhelper operating on the user class? username and phone are also properties of user.

**Comment by rouilj** [comment]
This is important for parity with existing classhelper.

**Comment by rouilj** [comment]
Ah sorry, I was being dense when I wrote my last comment. Yes, roles are a property, but they are not
a linked class that you can query. The answer is hinted at by:

  https://roundup-tracker.org/docs/rest.html#controlling-access-to-backend-data

by adding a REST endpoint. I am not sure if you can use that method to add:

  tracker.../data/user/role

I'll try it. However, you can set up searching on an issue by title (text search) and keyword, status or priority as dropdowns as keyword, status and priority are true classes.

**Comment by patel-malav** [comment]
This is what is followed up with and is ready to be reviewed

**Comment by rouilj** [comment]
I can't get '/rest/data/user/role' or '/rest/data/role' to work, but I do have '/rest/role' working.

Create the file `interfaces.py` in your tracker home directory and add:
```
from roundup.rest import Routing, RestfulInstance,  _data_decorator

class RestfulInstance:

    @Routing.route("/roles", 'GET')
    @_data_decorator
    def get_roles(self, input):
        """Return all defined roles. The User class property
           roles is a string but simulate it as a MultiLink
           to an actual Roles class.
        """
        return 200, {"collection": [ {"id": rolename, "name": rolename}
                  for rolename in list(self.db.security.role.keys())]}
```

Restart your tracker and query:

  http://localhost:8080/demo/rest/roles

which returns a list of roles like:
```
{
    "data": {
        "collection": [
            {
                "id": "user",
                "name": "user"
            },
            {
                "id": "admin",
                "name": "admin"
            },
            {
                "id": "anonymous",
                "name": "anonymous"
            }
        ]
    }
}
```

Note that the `id` can't be interpreted as an integer because we are faking a real database
class. The shape of the data can be made simpler if we want. I chose this shape to match
what you see when querying a real class endpoint like `/rest/data/status`.

**Comment by rouilj** [comment]
Hi Malav:

> roles[]<<sortorder>>

ne other thing to consider is that some classes may not have a "name" property that you are using in your fields request. I have written comments on the pull request about using `?@verbose=2` to get the key field included automatically. You can use both `@fields` and `@verbose`, they are additive.

I like your syntax here as I think it could help solve the issue. Suppose we allowed:

   roles[<<KeyField>>]<<sortorder>>

this might make things easier if identifying the key field from the returned `@verbose=2` is difficult.

**Comment by rouilj** [comment]
It looks like extracting the property name from `keyword[]+name` isn't right. When searching superseder by keyword, the
label is `keyword[]+name` and the rest request is:

```
GET /demo/rest/data/issue?%40page_index=1&%40page_size=50&%40fields=id%2Ctitle&%40sort=title&keyword%5B%5D-name=key1
```
when looking for issues with the key1 keyword.  `%5B` => `[` `%5D` => `]`. This is using current main. Maybe your changes
got out of sync and the new syntax for searchwith got deployed to main in the template but the code to back it in classhelper.js did not?

**Comment by rouilj** [comment]
Syntax for this is done. It is available on main. Other work on this to be done on separate issues.
There is an easy way to determine the new key field that is added.

Mentioned it in standup and commented in review notes on https://github.com/UMB-CS-682-Team-03/tracker/commit/67a3ab4988f2e4b32077aa41a875907613894444
