### ISSUE TITLE
Making the Disabled buttons for pagination invisible

### ISSUE THREAD

**Issue by Nikunj-1308** [UMB-CS-682-Team-03/tracker#32]

**Comment by rouilj** [comment]
Another possibility I like better is to use visibility: hidden for a disabled button in the popup-pagination.

e.g.

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/c630257f-6a6f-41ac-8655-6add1fd6a3da)

visible keeps the space for the button but doesn't display it so the count is kept in it's usual position.

**Comment by Nikunj-1308** [comment]
I have updated the button to look more disabled.
![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/36291317/4b43c1fe-e71c-45cf-9494-25dae64881c4)

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/36291317/c1b70cad-aa35-4ade-995b-9633d638ef27)
