### ISSUE TITLE
Clicking on classhelper link multiple times opens multiple popups, should open one and move/focus it in foreground on click.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#37]
With the classic classhelper link, clicking on the link to open the popup it reuses the window  and
moves the existing open popup to the foreground (while resetting the internal contents 8-().

When clicking the link with the web component a new window is popped up. This is fine if it's for a different
classhelper link. But if I click twice on the same classhelper link, I should only get the already open popup moved to
the foreground.

It would be nice to have this selectable in the component:
```
<roundup-classhelper multiwindow=1>
```
as I can see a use case for having multiple windows open. But this requires that the user be careful to not Apply the
wrong window. Basically having multiple windows like this is a footgun that should not happen.

If the easiest way to handle this is to have only one popup window at a time (rather than one per property) I am ok
with that, as we have that now.

**Comment by rouilj** [comment]
Hmm, this looks like it works when put at the top of opePopUp.

```
      if (this.popupRef && ! this.popupRef.closed) {
          this.popupRef.focus();
	  return;
      }
```

If the popup is closed with cancel, apply or [x] button supplied by the os, this allows openPopUp to open
a new window.

It worked for me raising the window from minimized or just buried under other windows with firefox and
chrome on linux.

I found reports where `.focus()` doesn't raise it to the top, you need a browser setting. 
If it doesn't work you can .close() and .open() it losing any of the current work (which is
effectively what the classic classhelper does). I think preserving the work is more important.

Originally I tried to register and eventhandler on window close. Figured I could set pageRef to null on close.
There are 4 different events. Two of which are not recommended (beforeunload/unload). Visibility and pagehide
don't fit the bill. Gave up on the event handler idea.

**Comment by patel-malav** [comment]
The focus() method works out flawless on firefox and chrome as well as brave, at the time of working I was using 

https://github.com/dr460nf1r3/firedragon-browser (Its default browser from my linux distribution Garuda Linux based on Firefox)

The focus method works there as well, reverting to using that
