### ISSUE TITLE
Add a title to the classhelper component

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#38]
Give the classhelper window a title like:

  selector for superseder

or if the popup is in info mode

   info for priority

This is the simplest way to id the window.

For reference, the classic helper uses: `nosy help - roundup issue tracker` so it's the form `<property> help - <tracker name from config.ini>`

Future enhancements (out of scope due to time for this issue) could include:

 * Passing the tracker name in via an attribute on the roundup-classhelper component and using it in the title
 * Fetching the class and item number from the url (or via attributes) and using it like: `selector for superseder issue 32`.

**Comment by rouilj** [comment]
Slight change in format for the title, let's try:

```
  propertyName - itemDesignator - class helper
```
Examples:
```
superseder - issue3 - class helper

nosy - issue45 - class helper

user23 - class helper
```
This lets the user know what property they are setting and what issue the popup is for if they
have multiple issues in flight.

The last title is displayed in the case where #35 is implemented and there is no property set (props.formProperty is missing/empty) for the classhelper (read only mode for classhelper).

Also if it's not too difficult, consider adding a `data-popup-title` attribute to the classhelper so the admin
can tune the title and set a title like:  "priority - {itemDesignator} - information' where {itemDesignator}
gets replaced by the designator (issue3, user23) of the parent form.

**Comment by patel-malav** [comment]
The commit - https://github.com/UMB-CS-682-Team-03/tracker/commit/61916203a794bebc34b8734f9e3335050b25ccfe adds the data-popup-title and also fixes the case when proprtyName is missing

**Comment by rouilj** [comment]
LGTM. Closing.
