### ISSUE TITLE
commit 27866f2b2 brought back poor selection table layout.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#39]
It looks like ref 27866f2b2 added:
```
table-layout: fixed;
```
to the selection table. This has brought this back:

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/7f45f0a4-a7b5-4d04-8772-16d7ad12ad31)

note the wide ID column, and the title header not continuing to the end of the data in the table.
the horizontal scroll bar is due to overflow of the title data.

If I set table-layout to auto (the default) I see:

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/2b9ef7aa-0c3e-49fa-aee3-7f2553fe6bac)

where the ID column size makes sense, the table header/footer continue to the end of the window at any size.
If I shrink the window down I get a horizontal scroll bar like the picture above.

What was the issue that required table-layout to be set to fixed? The log message for the mega refactoring
commit didn't address this.

**Comment by patel-malav** [comment]
This was verified in the last sprint, closing the Issue
