### ISSUE TITLE
When an error is handled we need better info about the input and error.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#40]
I have  had a few errors on the back end that made the REST calls fail. It seems to silently fail
and I don't see any output in console or displayed to user. Also it unregistered the web-component
without saying anything.

At the very least add:

  1) a warning to the console when the web component isn't intercepting the link
  2) display any thrown errors in the console at warning level or higher

**Comment by patel-malav** [comment]
This was completed in https://github.com/UMB-CS-682-Team-03/tracker/commit/84d2da9a7840f7949ee9dae9133aa60fc3b08574 closing the issue
