### ISSUE TITLE
** Commit 5bea1e17 is producing unpopulated selection areas and no accumulators.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#44]
Not sure when this happened but I am running 5bea1e17 and I see this when clicking on the superseder, nosy and keyword classhelper links:

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/8d2e8b8f-733c-4066-9230-e7584a84778c)

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/ec5262eb-34e5-4216-9545-f4416a947b9f)

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/35bd0915-a163-458e-8d81-762833658efd)

I have purged all caches and verify I have no material changes to the commit's classhelper.js.
(I add a newline after `enableClassHelper();`.)

**Comment by rouilj** [comment]
It looks like 67be4a34466 works as expected. So do not commit on top of 5bea1e17  for now.

So somebody **BROKE THE BUILD** 8-).

**Comment by patel-malav** [comment]
I know this I broke it, an undefined variable is being used
