### ISSUE TITLE
How to scroll table if it overflows the classhelper

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#45]
We have a table inside a div and the div is set to overflow auto. This was to allow the table to be scrolled left/right
as well as up/down. Space when the div is selected allows scrolling the table up/down. Also up/down arrow keys
(except when wrapping from the bottom of table to top)  and tab scroll the table up/down.

The arrow left/right arrow keys I think were used for horizontal scrolling by browser default. However they are used for back/forward page (#28). Maybe we should rethink that.

Back/forward page could be assigned to shift left/right arrow or '>' '<' keys maybe?

**Comment by patel-malav** [comment]
Completed last sprint
