### ISSUE TITLE
change name of searchWith attribute to data-searchWith

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#47]
One thing to check is that attributeChangedCallback is called when data-searchWith is changed.

Idea from: https://adactio.com/journal/21078

===
Naming attributes

You can use any attributes you want on a web component. You made up the name of the custom element and you can make up the names of the attributes too.

I’m a little nervous about this. What if HTML ends up with a new global attribute in the future that clashes with something I’ve invented? It’s unlikely but it still makes me wary.

So I use data- attributes. I’ve already got a hyphen in the name of my custom element, so it makes sense to have hyphens in my attributes too. And by using data- attributes, the browser gives me automatic reflection of the value in [the dataset property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset).

Instead of getting a value with this.getAttribute('maximum') I get to use this.dataset.maximum. Nice and neat.

===

**Comment by patel-malav** [comment]
commit 6f2e0380a688ce6cdeb76408f3f22abd5f6d26fb has the refactored changes

**Comment by rouilj** [comment]
LGTM.
