### ISSUE TITLE
Fix counter when there are no results

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#48]
If I open the classhelper for superseder and choose a keyword that no issue uses I see the following:

![image](https://github.com/UMB-CS-682-Team-03/tracker/assets/3751752/2f02ced6-c285-45c6-bda4-6dc76724e623)

This should probably be '0 - 0' not '1 - 0'.

Fixing this to show 0 - 0 (which does not need translation) or "no issues found" (which should be eligible for translation) when on page 1 and there is nothing to show will complete the issue.

--------------------
This is a case of an empty state.

See:

  *  https://www.nngroup.com/articles/empty-state-interface-design/
  * https://app.uxcel.com/courses/common-patterns/empty-states-best-practices-330

for more info. If we had more time, I would brainstorm with you as to how we could better inform the user.
E.G. have the selection pane show the statement:

   There are no issues using the keyword 'hey'. Change your search inputs and search again.

but for now we will just follow roundup's default with an empty 'empty state'.

**Comment by patel-malav** [comment]
Commit - d4a0c0a2fc50115b95d2b5bf708fd82dbfe953bc
