### ISSUE TITLE
Is splinter required for the test suite? 

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#50]
README.md says that splinter is required for running the test suite. But I can run it with just the selenium
module installed. Is Splinter really required?

If not please update README.md removing the splinter references.

**Comment by patel-malav** [comment]
@BharathKanama answered that this is not a requirement.

He has updated the documentation to not include this

Doc changes - https://github.com/UMB-CS-682-Team-03/tracker/commit/d1464106d21c21c4abe0a591afb94fc7771265c9

Closing the Issue
