### ISSUE TITLE
Refresh directions for classhelper.css doesn't seem to work - with workaround

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#53]
I made a simple change (set color for disabled prev/next buttons) and followed the refresh directions in README.md.

I still have the old css. Explicitly opening:

```
http://localhost:8080/demo/@@file/classhelper.css
```
in a new tab of the same browser and hard refreshing that shows the file with the changes.
Now opening a popup gets the new styles.

change README.md to use this method.

**Comment by patel-malav** [comment]
Doc were updated - https://github.com/UMB-CS-682-Team-03/tracker?tab=readme-ov-file#refreshing-classhelpercss

**Comment by patel-malav** [comment]
Closing this Issue
