### ISSUE TITLE
Is there an accellerator key for accessing the accumulator/submit part of the classhelper?

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#55]
We have '<' and '>' for accessing the pagination component. It would be good to have one for jumping from the
table to the accumulator. I suggest having it work like '<' by changing focus to accept when the button is pressed and require the user to press enter to actually accept the change.

I don't have a key in mind though. Maybe shift-enter to move and the enter to take it? Not discoverable but
it kind of makes sense to me???

**Comment by patel-malav** [comment]
We have used Shift + Enter to jump to the apply button and press enter again to apply changes
