### ISSUE TITLE
Patch test_classhelper.py and classhelper.css after commit 7de6f75c47 changed markers used by testing/css

### ISSUE THREAD

**Issue by rouilj** [UMB-CS-682-Team-03/tracker#58]
Commit 7de6f75c47 to remove checkboxes when the classhelper is used in read-only mode also changed:

  | From | To |
  | ----     |--    |
  | .acc-apply  | .popup-apply |
  | .rowstyle    | .row-style    |

This had a couple of effects downstream. The css that made the apply button bold needed to be changed from .acc-apply. Also the test_classhelper.py made extensive use of both acc-apply and rowstyle in locating the elements it wanted to interact with.

I assume these changes snuck (sneaked) into the commit by accident probably as part of another cleanup that
would have included the tests and css.

The diff/patch is attached. I also extracted the testing URL to a variable as I was testing against the real
name of my server at home rather than localhost.

[test_and_css_patches.patch.txt](https://github.com/UMB-CS-682-Team-03/tracker/files/15328978/test_and_css_patches.patch.txt)

**Comment by rouilj** [comment]
I forgot to mention that the classhelper data-search-with for superseder got change and replaced `status[]` with `status`. This also broke a test as it was looking for a select input not a text input. So I needed to change
that in issue.item.html.

**Comment by patel-malav** [comment]
PR - https://github.com/UMB-CS-682-Team-03/tracker/pull/60

I will test this in windows and do a merge

**Comment by patel-malav** [comment]
I have tested it in linux and windows, testing suit works on both.
